apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: https://github.com/andrey-parkhomets/gitops.git
    path: registry/kubefirst/components/atlantis
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true