---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst-kubedoom-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '100'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrey-parkhomets/gitops.git
    path: clusters/kubefirst/components/kubedoom
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: kubedoom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
