apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://charts.konstruct.io
    targetRevision: 2.8.4
    chart: kubefirst-pro
    helm:
      values: |-
        global:
          cloudProvider: "k3d"
          clusterId: "277f6q"
          clusterType: "mgmt"
          domainName: "kubefirst.dev"
          gitProvider: "github"
          installMethod: "helm"
          kubefirstClient: "<KUBEFIRST_CLIENT>"
          kubefirstTeam: "false"
          kubefirstTeamInfo: "<KUBEFIRST_TEAM_INFO>"
          kubefirstVersion: "v2.8.4"
          useTelemetry: "false"
        kubefirst-pro-api:
          extraEnv:
            CLUSTER_NAME: "kubefirst"
        kubefirst-pro-ui:
          domain: "kubefirst.dev"
          isK3d: "true"
          extraEnv:
            DISABLE_AUTH: "true"
          extraEnvSecrets:
            CLIENT_ID:
              name: kubefirst-console-secrets
              key: client_id
            SECRET_ID:
              name: kubefirst-console-secrets
              key: client_secret
          ingress:
            enabled: "true"
            hosts:
              - host: kubefirst.kubefirst.dev
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubefirst-tls
                hosts:
                  - kubefirst.kubefirst.dev
  destination:
    name: in-cluster
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
