---
repos:
  - id: /.*/
    apply_requirements:
      - mergeable
      - approved
    allowed_overrides:
      - workflow
    allow_custom_workflows: false
    workflow: noworkflow
workflows:
  noworkflow:
    plan:
      steps:
        - run: echo "No Workflow Configured, Doing Nothing!!!! "
  dev:
    plan:
      steps:
        - run: echo "===== Plan Stage"
        - env:
            name: ARM_SUBSCRIPTION_ID
            value: 16311667-b599-473f-b4c6-0152bace79a0
        - env:
            # Reduce Terraform suggestion output
            name: TF_IN_AUTOMATION
            value: 'true'
        - init
        - plan

    apply:
      steps:
        - run: echo "===== Apply Stage"
        - env:
            name: ARM_SUBSCRIPTION_ID
            value: 16311667-b599-473f-b4c6-0152bace79a0
        - env:
            # Reduce Terraform suggestion output
            name: TF_IN_AUTOMATION
            value: 'true'
        - apply
