name: Clean Cache
on:
  pull_request:
    types: [closed]


jobs:
  clean-cache:
    runs-on: ubuntu-latest
    container:
      image: maniator/gh:latest
    steps:
      - name: Clean Atlantis Cache
        run: |
          gh cache delete atlantis-data-${PR_NUMBER} || (exit 0)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
